/* ==========================================================
 * 学成选择题 · 西综306刷题系统  — app.js
 * Generated by Trae Work
 * ========================================================== */

/* ====== 3.1 样例题目 ====== */
const SAMPLE_QUESTIONS = [
  {
    id:'q001', subject:'pathology', system:'digestive', chapter:'慢性胃炎',
    type:'matching', title:'慢性胃炎 · A型 vs B型胃炎',
    description:'将下列特征归类到对应的慢性胃炎类型',
    options:[
      {id:'A',text:'自身免疫性'},{id:'B',text:'Hp感染'},
      {id:'C',text:'胃体为主'},{id:'D',text:'胃窦为主'},
      {id:'E',text:'胃酸降低'},{id:'F',text:'胃酸正常/稍低'},
      {id:'G',text:'壁细胞抗体阳性'},{id:'H',text:'G细胞增生'}
    ],
    categories:[{id:'C1',label:'A型胃炎（自身免疫性）'},{id:'C2',label:'B型胃炎（Hp感染）'}],
    answer:{A:'C1',B:'C2',C:'C1',D:'C2',E:'C1',F:'C2',G:'C1',H:'C2'},
    explanation:'A型=自身免疫性+胃体+胃酸↓+壁细胞抗体阳性+G细胞增生→胃泌素↑；B型=Hp感染+胃窦+胃酸正常/稍低。关键鉴别：病变部位(胃体vs胃窦)+病因(自身免疫vsHp)+胃酸(↓vs正常)。'
  },
  {
    id:'q002', subject:'pathology', system:'digestive', chapter:'肝硬化',
    type:'matching', title:'肝硬化 · 肝功能减退 vs 门脉高压',
    description:'将下列表现归类到对应的肝硬化临床综合征',
    options:[
      {id:'A',text:'白蛋白↓'},{id:'B',text:'凝血因子↓'},
      {id:'C',text:'蜘蛛痣'},{id:'D',text:'肝掌'},
      {id:'E',text:'脾大'},{id:'F',text:'腹水'},
      {id:'G',text:'食管胃底静脉曲张'},{id:'H',text:'黄疸'}
    ],
    categories:[{id:'C1',label:'肝功能减退综合征'},{id:'C2',label:'门脉高压综合征'}],
    answer:{A:'C1',B:'C1',C:'C1',D:'C1',E:'C2',F:'C2',G:'C2',H:'C1'},
    explanation:'肝功能减退：合成↓(白蛋白、凝血因子)、灭活↓(雌激素↑→蜘蛛痣/肝掌)、胆红素代谢障碍(黄疸)。门脉高压：脾大(脾淤血)、腹水(门脉压↑+低蛋白)、侧支循环建立(食管胃底静脉曲张)。注意：腹水两者均可导致，但主要归入门脉高压。'
  },
  {
    id:'q003', subject:'pathology', system:'digestive', chapter:'消化性溃疡',
    type:'matching', title:'消化性溃疡 · 胃溃疡 vs 十二指肠溃疡',
    description:'将下列特征归类到对应的消化性溃疡类型',
    options:[
      {id:'A',text:'餐后痛'},{id:'B',text:'空腹痛'},
      {id:'C',text:'夜间痛'},{id:'D',text:'制酸剂缓解快'},
      {id:'E',text:'胃酸正常/↓'},{id:'F',text:'胃酸↑'},
      {id:'G',text:'好发于胃窦/小弯'}
    ],
    categories:[{id:'C1',label:'胃溃疡(GU)'},{id:'C2',label:'十二指肠溃疡(DU)'}],
    answer:{A:'C1',B:'C2',C:'C2',D:'C2',E:'C1',F:'C2',G:'C1'},
    explanation:'GU：餐后痛(进食→胃酸分泌→刺激溃疡面)、胃酸正常/↓、好发胃窦小弯。DU：空腹痛/夜间痛(胃酸无食物中和)、制酸剂缓解快、胃酸↑。关键鉴别：疼痛节律(餐后vs空腹)+胃酸水平。'
  },
  {
    id:'q004', subject:'pathology', system:'cardiovascular', chapter:'感染性心内膜炎',
    type:'matching', title:'感染性心内膜炎 · 急性 vs 亚急性',
    description:'将下列特征归类到对应的感染性心内膜炎类型',
    options:[
      {id:'A',text:'金黄色葡萄球菌'},{id:'B',text:'草绿色链球菌'},
      {id:'C',text:'正常瓣膜'},{id:'D',text:'病变瓣膜'},
      {id:'E',text:'急起高热'},{id:'F',text:'缓慢起病'},
      {id:'G',text:'瓣膜破坏严重'},{id:'H',text:'栓塞常见'}
    ],
    categories:[{id:'C1',label:'急性感染性心内膜炎'},{id:'C2',label:'亚急性感染性心内膜炎'}],
    answer:{A:'C1',B:'C2',C:'C1',D:'C2',E:'C1',F:'C2',G:'C1',H:'C2'},
    explanation:'急性IE：金葡菌+正常瓣膜+急起高热+瓣膜破坏严重(赘生物大易脱落)。亚急性IE：草绿色链球菌+病变瓣膜+缓慢起病+栓塞常见。关键鉴别：病原体毒力+基础瓣膜情况+起病速度。'
  },
  {
    id:'q005', subject:'pathology', system:'respiratory', chapter:'肺炎',
    type:'matching', title:'大叶性肺炎 vs 小叶性肺炎',
    description:'将下列特征归类到对应的肺炎类型',
    options:[
      {id:'A',text:'肺炎链球菌'},{id:'B',text:'葡萄球菌等多种菌'},
      {id:'C',text:'大叶实变'},{id:'D',text:'小叶散在病变'},
      {id:'E',text:'青壮年'},{id:'F',text:'老弱病残'},
      {id:'G',text:'铁锈色痰'},{id:'H',text:'脓性痰'}
    ],
    categories:[{id:'C1',label:'大叶性肺炎'},{id:'C2',label:'小叶性肺炎'}],
    answer:{A:'C1',B:'C2',C:'C1',D:'C2',E:'C1',F:'C2',G:'C1',H:'C2'},
    explanation:'大叶性肺炎：肺炎链球菌+大叶实变+青壮年+铁锈色痰(充血期红细胞渗出)。小叶性肺炎：多种菌(葡萄球菌等)+小叶散在+老弱病残+脓性痰(化脓性炎)。关键鉴别：病原体+病变范围+患者人群+痰液性质。'
  },
  {
    id:'q006', subject:'internal', system:'cardiovascular', chapter:'慢性心力衰竭',
    type:'matching', title:'慢性心力衰竭 · NYHA分级',
    description:'将下列活动耐量归类到对应的NYHA心功能分级',
    options:[
      {id:'A',text:'日常活动无症状'},{id:'B',text:'日常活动有症状'},
      {id:'C',text:'低于日常活动有症状'},{id:'D',text:'休息时即有症状'}
    ],
    categories:[
      {id:'C1',label:'NYHA I级'},{id:'C2',label:'NYHA II级'},
      {id:'C3',label:'NYHA III级'},{id:'C4',label:'NYHA IV级'}
    ],
    answer:{A:'C1',B:'C2',C:'C3',D:'C4'},
    explanation:'NYHA I级：日常活动无症状。II级：日常活动有症状(轻度受限)。III级：低于日常活动有症状(明显受限)。IV级：休息时即有症状(不能从事任何体力活动)。是心力衰竭严重程度的重要评估标准。'
  }
];

/* ====== 3.2 科目/系统元数据 ====== */
const SUBJECTS = {
  pathology:{name:'病理学',icon:'🫁',desc:'细胞损伤、炎症、肿瘤、各系统疾病'},
  internal:{name:'内科学',icon:'🫀',desc:'呼吸、循环、消化、泌尿、血液、内分泌'},
  surgery:{name:'外科学',icon:'🦴',desc:'普外、骨科、泌尿、胸外'},
  physiology:{name:'生理学',icon:'🧬',desc:'细胞、血液、循环、呼吸、消化'},
  biochem:{name:'生物化学',icon:'⚗️',desc:'蛋白质、酶、糖代谢、脂代谢'}
};

const SYSTEMS = {
  pathology:{
    digestive:{name:'消化系统疾病',chapters:[
      {id:'chronic_gastritis',name:'慢性胃炎 · A型 vs B型'},
      {id:'cirrhosis',name:'肝硬化 · 临床表现分类'},
      {id:'peptic_ulcer',name:'消化性溃疡 · 胃溃疡 vs 十二指肠'}
    ]},
    cardiovascular:{name:'心血管系统疾病',chapters:[
      {id:'endocarditis',name:'感染性心内膜炎 · 急性 vs 亚急性'}
    ]},
    respiratory:{name:'呼吸系统疾病',chapters:[
      {id:'pneumonia',name:'肺炎 · 大叶性 vs 小叶性'}
    ]}
  },
  internal:{
    cardiovascular:{name:'循环系统疾病',chapters:[
      {id:'heart_failure',name:'慢性心力衰竭 · NYHA分级'}
    ]}
  }
};

/* ====== 3.15 艾宾浩斯复习模式 ====== */
const MODES = {
  minimal: { name:'极简模式', nodes:[1,2,7], labels:['观看录播','做题巩固','错题重练'] },
  errorOnly: { name:'仅错题复习', nodes:[], labels:[], isErrorMode:true }
};

/* ====== 3.4 状态管理 ====== */
let db;
let currentUserId = 1;
let currentUserName = 'Rosy1003';
let currentMode = 'minimal';
let currentSubject = null;
let currentSystem = null;
let currentQuestions = [];
let currentQuestionIndex = 0;
let quizState = { selectedOption:null, placements:{}, answered:false };
let allQuestions = [];
let currentNoteTarget = null;
let currentNoteImages = [];
let favoritedIds = new Set();
let wrongFilterSubject = 'all';
let noteFilterSubject = 'all';
let autoSyncEnabled = false;
let shuffleOptionsEnabled = false;
let darkModeEnabled = false;

const PANEL_TITLES = { home:'首页总览', quiz:'刷题练习', wrong:'错题本', stats:'学习统计', fav:'收藏夹', notes:'我的解析', settings:'设置' };
const USER_COLORS = ['#9a8e82','#7d9e7d','#7a95b0','#a08eb0','#c9a96a','#b87a7a'];

/* ==========================================================
 * 3.3 IndexedDB 实现
 * ========================================================== */
const DB_NAME = 'xuecheng_quiz_db';
const DB_VERSION = 1;
const STORES = ['records','wrongQuestions','favorites','notes','users','questions','settings'];

function initDB(){
  return new Promise((resolve,reject)=>{
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = (e)=>{
      const _db = e.target.result;
      STORES.forEach(store=>{
        if(!_db.objectStoreNames.contains(store)){
          _db.createObjectStore(store, { keyPath:'id' });
        }
      });
    };
    req.onsuccess = (e)=>{ db = e.target.result; resolve(); };
    req.onerror = (e)=>{ console.error('IndexedDB 打开失败', e.target.error); reject(e.target.error); };
  });
}

function dbAdd(store, data){
  return new Promise((resolve,reject)=>{
    const tx = db.transaction(store,'readwrite');
    tx.objectStore(store).put(data);
    tx.oncomplete = ()=>resolve();
    tx.onerror = ()=>reject(tx.error);
  });
}

function dbGetAll(store){
  return new Promise((resolve,reject)=>{
    const tx = db.transaction(store,'readonly');
    const req = tx.objectStore(store).getAll();
    req.onsuccess = ()=>resolve(req.result||[]);
    req.onerror = ()=>reject(req.error);
  });
}

function dbGetByKey(store, key){
  return new Promise((resolve,reject)=>{
    const tx = db.transaction(store,'readonly');
    const req = tx.objectStore(store).get(key);
    req.onsuccess = ()=>resolve(req.result);
    req.onerror = ()=>reject(req.error);
  });
}

function dbDelete(store, id){
  return new Promise((resolve,reject)=>{
    const tx = db.transaction(store,'readwrite');
    tx.objectStore(store).delete(id);
    tx.oncomplete = ()=>resolve();
    tx.onerror = ()=>reject(tx.error);
  });
}

function dbClear(store){
  return new Promise((resolve,reject)=>{
    const tx = db.transaction(store,'readwrite');
    tx.objectStore(store).clear();
    tx.oncomplete = ()=>resolve();
    tx.onerror = ()=>reject(tx.error);
  });
}

/* ====== 工具函数 ====== */
function userColor(id){
  return USER_COLORS[(id-1) % USER_COLORS.length];
}
function todayStr(){ return new Date().toDateString(); }
function escapeHtml(s){
  return String(s==null?'':s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
function formatDate(d){
  const dt = new Date(d);
  return `${dt.getMonth()+1}月${dt.getDate()}日`;
}

/* ==========================================================
 * 3.5 面板切换
 * ========================================================== */
function switchPanel(name){
  document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));
  const target = document.getElementById('panel-'+name);
  if(target) target.classList.add('active');
  document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active', n.dataset.panel===name));
  document.querySelectorAll('.mobile-nav-item').forEach(n=>n.classList.toggle('active', n.dataset.panel===name));
  document.getElementById('pageTitle').textContent = PANEL_TITLES[name] || name;
  if(name==='home') renderHome();
  if(name==='quiz') renderQuiz();
  if(name==='wrong') renderWrong();
  if(name==='stats') renderStats();
  if(name==='fav') renderFavorites();
  if(name==='notes') renderNotes();
  if(name==='settings') renderSettings();
}

/* ==========================================================
 * 3.6 刷题逻辑（点击式匹配）
 * ========================================================== */
async function renderQuiz(){
  const el = document.getElementById('quizContent');
  const records = (await dbGetAll('records')).filter(r=>r.userId===currentUserId);

  // 模式选择器
  let modeHtml = '<div class="mode-selector">';
  Object.entries(MODES).forEach(([key,m])=>{
    const nodesText = m.isErrorMode ? '无时间限制' : m.nodes.join(' → ') + ' 天';
    modeHtml += `<div class="mode-card ${key===currentMode?'active':''}" onclick="selectMode('${key}')">
      <div class="mc-title">${m.name}</div>
      <div class="mc-nodes">${nodesText}</div>
      ${key===currentMode?'<div class="mc-badge">当前</div>':''}
    </div>`;
  });
  modeHtml += '</div>';

  // 科目网格
  let gridHtml = '<div class="quiz-subject-grid">';
  Object.entries(SUBJECTS).forEach(([key,sub])=>{
    const subQuestions = allQuestions.filter(q=>q.subject===key);
    const subRecords = records.filter(r=>r.subject===key);
    const doneSet = new Set(subRecords.map(r=>r.questionId));
    const progress = subQuestions.length>0 ? Math.round(doneSet.size/subQuestions.length*100) : 0;
    gridHtml += `<div class="quiz-sub-card" onclick="enterSubject('${key}')">
      <div class="qsc-icon">${sub.icon}</div>
      <div class="qsc-name">${sub.name}</div>
      <div class="qsc-desc">${sub.desc}</div>
      <div class="qsc-stats">
        <span>📝 ${subQuestions.length}题</span>
        <span>✓ 已做${doneSet.size}</span>
      </div>
      <div class="qsc-progress"><div class="qsc-progress-fill" style="width:${progress}%;background:${userColor(1)}"></div></div>
    </div>`;
  });
  gridHtml += '</div>';

  el.innerHTML = modeHtml + '<h3 style="font-size:1rem;margin:1.2rem 0 .8rem">选择科目开始刷题</h3>' + gridHtml;
}

function enterSubject(subject){
  currentSubject = subject;
  const el = document.getElementById('quizContent');
  const sub = SUBJECTS[subject];
  const sysData = SYSTEMS[subject] || {};
  const records = [];

  let html = `<button class="btn btn-outline" style="margin-bottom:1rem" onclick="backToSubjects()">← 返回科目</button>`;
  html += `<h3 style="font-size:1.1rem;margin-bottom:1rem">${sub.icon} ${sub.name}</h3>`;

  if(Object.keys(sysData).length === 0){
    html += `<div class="empty-state"><div class="es-icon">📭</div><p>该科目暂无题库内容</p></div>`;
  } else {
    html += '<div class="system-list show">';
    Object.entries(sysData).forEach(([sysKey,sys])=>{
      html += `<div class="system-group">
        <div class="system-header open" onclick="this.classList.toggle('open');this.nextElementSibling.classList.toggle('show')">
          <span class="sh-name">${sys.name}</span>
          <span class="sh-toggle">▾</span>
        </div>
        <div class="system-chapters show">`;
      sys.chapters.forEach(ch=>{
        const chQuestions = allQuestions.filter(q=>q.subject===subject && q.system===sysKey && ch.name.includes(q.chapter));
        const count = chQuestions.length;
        html += `<div class="chapter-row" onclick="startQuiz('${subject}','${sysKey}','${ch.id}','${escapeHtml(ch.name)}')">
          <div class="ch-row-left"><span>📄</span><span>${ch.name}</span></div>
          <div class="ch-row-right">
            <span class="ch-count">${count}题</span>
            <button class="ch-btn">开始 →</button>
          </div>
        </div>`;
      });
      html += `</div></div>`;
    });
    html += '</div>';
  }

  el.innerHTML = html;
}

function backToSubjects(){
  currentSubject = null;
  renderQuiz();
}

async function startQuiz(subject, system, chapterId, chapterName){
  currentSubject = subject;
  currentSystem = system;
  // 按章节精确匹配，回退到科目+系统
  let qs = allQuestions.filter(q=>q.subject===subject && q.system===system && chapterName.includes(q.chapter));
  if(qs.length===0){
    qs = allQuestions.filter(q=>q.subject===subject && q.system===system);
  }
  currentQuestions = qs;
  currentQuestionIndex = 0;
  // 加载收藏状态
  const favs = (await dbGetAll('favorites')).filter(f=>f.userId===currentUserId);
  favoritedIds = new Set(favs.map(f=>f.questionId));
  renderQuestion();
}

async function renderQuestion(){
  const q = currentQuestions[currentQuestionIndex];
  const el = document.getElementById('quizContent');
  if(!q){
    el.innerHTML = '<div class="empty-state"><div class="es-icon">📭</div><p>该章节暂无题目</p></div>';
    return;
  }
  quizState = { selectedOption:null, placements:{}, answered:false };
  const progress = currentQuestions.length>0 ? ((currentQuestionIndex+1)/currentQuestions.length*100).toFixed(0) : 0;
  
  // 打乱选项顺序（仅影响显示，不影响答案判定，因答案按 ID 映射）
  if(shuffleOptionsEnabled && q.options && q.options.length>1){
    q._displayOptions = [...q.options];
    for(let i=q._displayOptions.length-1;i>0;i--){
      const j = Math.floor(Math.random()*(i+1));
      [q._displayOptions[i],q._displayOptions[j]] = [q._displayOptions[j],q._displayOptions[i]];
    }
  } else {
    q._displayOptions = q.options;
  }
  
  // 获取该题的对错次数
  const allRecords = await dbGetAll('records');
  const qRecords = allRecords.filter(r=>r.userId===currentUserId && r.questionId===q.id);
  const correctCount = qRecords.filter(r=>r.correct).length;
  const wrongCount = qRecords.filter(r=>!r.correct).length;
  const totalCount = qRecords.length;

  el.innerHTML = `
    <div class="quiz-player show">
      <div class="quiz-area">
        <div class="quiz-header">
          <div class="quiz-title">${escapeHtml(q.title)}</div>
          <div class="quiz-progress">第 <strong>${currentQuestionIndex+1}</strong> / ${currentQuestions.length} 题</div>
        </div>
        <div class="progress-bar-wrap"><div class="progress-fill" style="width:${progress}%"></div></div>
        <div style="display:flex;gap:.5rem;margin-bottom:.6rem;flex-wrap:wrap">
          <span style="background:var(--green-bg);color:var(--green);padding:.15rem .6rem;border-radius:6px;font-size:.72rem;font-weight:600">✅ 正确 ${correctCount}次</span>
          <span style="background:var(--red-bg);color:var(--red);padding:.15rem .6rem;border-radius:6px;font-size:.72rem;font-weight:600">❌ 错误 ${wrongCount}次</span>
          <span style="background:var(--yellow-bg);color:var(--yellow);padding:.15rem .6rem;border-radius:6px;font-size:.72rem;font-weight:600">📋 共做 ${totalCount}次</span>
        </div>
        <div style="font-size:.85rem;color:var(--muted);margin-bottom:1rem">${escapeHtml(q.description)}</div>
        <div class="matching-layout">
          <div class="option-pool">
            <div class="pool-title">📋 选项池（点击选项 → 再点击分类卡片放入）</div>
            <div class="pool-items" id="optionPool"></div>
          </div>
          <div class="category-area" id="categoryArea">
            ${q.categories.map((cat,i)=>`
              <div class="category-card" data-cat="${cat.id}" id="cat-${cat.id}" onclick="selectCategory('${cat.id}')">
                <div class="cat-label">
                  <span class="q-icon">${i+1}</span>
                  ${escapeHtml(cat.label)}
                  <span class="cat-status" id="cat-status-${cat.id}"></span>
                </div>
                <div class="placed-list" id="placed-${cat.id}"></div>
              </div>
            `).join('')}
          </div>
        </div>
        <div class="action-bar">
          <button class="btn btn-primary" id="submitBtn" onclick="submitAnswer()">提交答案</button>
          <button class="btn btn-primary" id="nextBtn" style="display:none" onclick="nextQuestion()">下一题 →</button>
          <button class="btn btn-outline" onclick="openNoteModal('${q.id}')">📝 添加解析</button>
          <button class="btn btn-outline" id="favBtn" onclick="toggleFavorite()">${favoritedIds.has(q.id)?'⭐ 取消收藏':'☆ 收藏'}</button>
          <button class="btn btn-outline" onclick="backToSubjects()">退出</button>
        </div>
        <div class="answer-reveal" id="answerReveal"></div>
      </div>
    </div>`;
  updateMatchingUI();
}

/* 重新渲染选项池与分类区（根据 quizState） */
function updateMatchingUI(){
  const q = currentQuestions[currentQuestionIndex];
  if(!q) return;

  // 选项池（使用打乱后的显示顺序）
  const pool = document.getElementById('optionPool');
  if(pool){
    const displayOpts = q._displayOptions || q.options;
    pool.innerHTML = displayOpts.map(opt=>{
      let cls = 'option-item';
      let style = '';
      if(quizState.placements[opt.id]) cls += ' placed';
      if(quizState.selectedOption===opt.id){
        style = 'border-color:var(--accent);background:var(--accent-bg);';
      }
      return `<div class="${cls}" data-opt="${opt.id}" style="${style}" onclick="selectOption('${opt.id}')">
        <span class="opt-letter">${opt.id}</span><span>${escapeHtml(opt.text)}</span>
      </div>`;
    }).join('');
  }

  // 分类卡片
  q.categories.forEach(cat=>{
    const card = document.getElementById('cat-'+cat.id);
    if(!card) return;
    if(quizState.answered){
      card.classList.remove('active-target');
    } else if(quizState.selectedOption){
      card.classList.add('active-target');
    } else {
      card.classList.remove('active-target');
    }
    // 已放置列表
    const placed = document.getElementById('placed-'+cat.id);
    if(placed){
      const placedOpts = q.options.filter(o=>quizState.placements[o.id]===cat.id);
      if(quizState.answered){
        // 答案揭示后显示对错
        if(placedOpts.length===0){
          placed.innerHTML = '<span class="empty-hint">未放置</span>';
        } else {
          placed.innerHTML = placedOpts.map(o=>{
            const ok = q.answer[o.id]===cat.id;
            return `<div class="placed-chip ${ok?'correct-chip':'wrong-chip'}">
              <span class="chip-letter">${o.id}</span>${escapeHtml(o.text)}
            </div>`;
          }).join('');
        }
      } else {
        if(placedOpts.length===0){
          placed.innerHTML = '<span class="empty-hint">点击选项后放入此处</span>';
        } else {
          placed.innerHTML = placedOpts.map(o=>
            `<div class="placed-chip" onclick="removePlacement('${cat.id}','${o.id}')">
              <span class="chip-letter">${o.id}</span>${escapeHtml(o.text)}<span class="chip-remove">✕</span>
            </div>`
          ).join('');
        }
      }
    }
  });
}

function selectOption(optId){
  if(quizState.answered) return;
  if(quizState.placements[optId]) return;
  // 再次点击同一个取消选中
  if(quizState.selectedOption===optId){
    quizState.selectedOption = null;
  } else {
    quizState.selectedOption = optId;
  }
  updateMatchingUI();
}

function selectCategory(catId){
  if(quizState.answered) return;
  if(!quizState.selectedOption) return;
  const optId = quizState.selectedOption;
  quizState.placements[optId] = catId;
  quizState.selectedOption = null;
  updateMatchingUI();
}

function removePlacement(catId, optId){
  if(quizState.answered) return;
  delete quizState.placements[optId];
  updateMatchingUI();
}

async function submitAnswer(){
  const q = currentQuestions[currentQuestionIndex];
  if(!q) return;
  quizState.answered = true;

  let correctCount=0, wrongCount=0, missedCount=0;

  // 标记选项
  q.options.forEach(opt=>{
    const el = document.querySelector(`.option-item[data-opt="${opt.id}"]`);
    const userCat = quizState.placements[opt.id];
    const correctCat = q.answer[opt.id];
    if(el){
      el.classList.remove('placed');
      el.style.borderColor='';
      el.style.background='';
      if(!userCat){
        missedCount++;
        el.classList.add('missed');
      } else if(userCat===correctCat){
        correctCount++;
        el.classList.add('correct');
      } else {
        wrongCount++;
        el.classList.add('wrong');
      }
    } else {
      if(!userCat) missedCount++;
      else if(userCat===correctCat) correctCount++;
      else wrongCount++;
    }
  });

  // 标记分类卡片
  q.categories.forEach(cat=>{
    const card = document.getElementById('cat-'+cat.id);
    if(!card) return;
    card.classList.remove('active-target');
    const placedOpts = q.options.filter(o=>quizState.placements[o.id]===cat.id);
    const correctForCat = q.options.filter(o=>q.answer[o.id]===cat.id);
    let allPlacedCorrect = placedOpts.length>0 && placedOpts.every(o=>q.answer[o.id]===cat.id);
    let noneMissing = correctForCat.every(o=>quizState.placements[o.id]===cat.id);
    if(allPlacedCorrect && noneMissing){
      card.classList.add('correct-target');
      const status = document.getElementById('cat-status-'+cat.id);
      if(status){ status.textContent='✓ 全部正确'; status.style.color='var(--green)'; }
    } else {
      card.classList.add('wrong-target');
      const status = document.getElementById('cat-status-'+cat.id);
      if(status){ status.textContent='✗ 有错误/遗漏'; status.style.color='var(--red)'; }
    }
  });

  updateMatchingUI();

  const total = q.options.length;
  const score = Math.round(correctCount/total*100);
  const isCorrect = wrongCount===0 && missedCount===0;

  // 答案揭示
  const reveal = document.getElementById('answerReveal');
  let ansRows = q.categories.map(cat=>{
    const correctOpts = q.options.filter(o=>q.answer[o.id]===cat.id).map(o=>`${o.id}.${o.text}`).join('；');
    return `<div class="ans-row"><span class="ans-cat">${escapeHtml(cat.label)}：</span><span class="ans-vals">${escapeHtml(correctOpts)}</span></div>`;
  }).join('');
  reveal.innerHTML = `
    <div class="score-bar">
      <div class="score-num" style="color:${isCorrect?'var(--green)':'var(--red)'}">${score}分</div>
      <div style="font-size:.82rem;color:var(--muted)">正确 ${correctCount} · 错误 ${wrongCount} · 遗漏 ${missedCount} ${isCorrect?'🎉 全部正确！':'继续加油！'}</div>
    </div>
    ${ansRows}
    <div class="ans-note">💡 ${escapeHtml(q.explanation)}</div>`;
  reveal.classList.add('show');

  // 切换按钮
  document.getElementById('submitBtn').style.display='none';
  document.getElementById('nextBtn').style.display='';

  // 记录到 IndexedDB
  await recordAnswer(q, isCorrect, score);
  // 错题处理
  if(isCorrect){
    await dbDelete('wrongQuestions', `wq_${currentUserId}_${q.id}`);
  } else {
    await addToWrongQuestions(q);
  }
  await updateWrongBadge();
  await updateUserStreak();

  // 自动同步
  if(autoSyncEnabled){
    try{ await syncToCloud(); }catch(e){ console.warn('自动同步失败',e); }
  }
}

function nextQuestion(){
  currentQuestionIndex++;
  if(currentQuestionIndex >= currentQuestions.length){
    showCompletion();
  } else {
    renderQuestion();
  }
}

function showCompletion(){
  const el = document.getElementById('quizContent');
  el.innerHTML = `
    <div class="quiz-player show">
      <div class="home-card" style="text-align:center;padding:3rem 2rem">
        <div style="font-size:3rem;margin-bottom:1rem">🎉</div>
        <h2 style="font-size:1.4rem;margin-bottom:.5rem">本章刷题完成！</h2>
        <p style="color:var(--muted);font-size:.88rem;margin-bottom:1.5rem">已完成 ${currentQuestions.length} 道题目，快去首页查看复习计划吧</p>
        <div class="action-bar" style="justify-content:center">
          <button class="btn btn-primary" onclick="renderQuiz()">返回科目选择</button>
          <button class="btn btn-outline" onclick="switchPanel('home')">查看首页</button>
          <button class="btn btn-outline" onclick="switchPanel('wrong')">查看错题</button>
        </div>
      </div>
    </div>`;
}

async function toggleFavorite(){
  const q = currentQuestions[currentQuestionIndex];
  if(!q) return;
  const id = `fav_${currentUserId}_${q.id}`;
  const existing = await dbGetByKey('favorites', id);
  if(existing){
    await dbDelete('favorites', id);
    favoritedIds.delete(q.id);
  } else {
    await dbAdd('favorites', {
      id, userId:currentUserId, questionId:q.id,
      subject:q.subject, system:q.system, chapter:q.chapter, title:q.title,
      question:q, addedDate:new Date().toISOString()
    });
    favoritedIds.add(q.id);
  }
  const btn = document.getElementById('favBtn');
  if(btn) btn.textContent = favoritedIds.has(q.id) ? '⭐ 取消收藏' : '☆ 收藏';
}

async function recordAnswer(q, isCorrect, score){
  const record = {
    id:`rec_${currentUserId}_${q.id}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,
    userId:currentUserId, questionId:q.id,
    subject:q.subject, system:q.system, chapter:q.chapter, title:q.title,
    correct:isCorrect, score:score,
    learnDate:new Date().toISOString(),
    learnDateStr:new Date().toDateString()
  };
  await dbAdd('records', record);
  // 更新错题的正确次数
  const wqId = `wq_${currentUserId}_${q.id}`;
  const existingWq = await dbGetByKey('wrongQuestions', wqId);
  if(existingWq){
    if(isCorrect){
      existingWq.correctCount = (existingWq.correctCount||0)+1;
      await dbAdd('wrongQuestions', existingWq);
    } else {
      existingWq.correctCount = existingWq.correctCount||0;
      await dbAdd('wrongQuestions', existingWq);
    }
  }
}

async function addToWrongQuestions(q){
  const id = `wq_${currentUserId}_${q.id}`;
  const existing = await dbGetByKey('wrongQuestions', id);
  if(existing){
    existing.wrongCount = (existing.wrongCount||0)+1;
    existing.lastWrongDate = new Date().toISOString();
    await dbAdd('wrongQuestions', existing);
  } else {
    await dbAdd('wrongQuestions', {
      id, userId:currentUserId, questionId:q.id,
      subject:q.subject, system:q.system, chapter:q.chapter, title:q.title,
      wrongCount:1, correctCount:0, lastWrongDate:new Date().toISOString(),
      question:q
    });
  }
}

/* ==========================================================
 * 3.7 首页仪表盘
 * ========================================================== */
async function renderHome(){
  const el = document.getElementById('homeContent');
  const records = (await dbGetAll('records')).filter(r=>r.userId===currentUserId);
  const wrongQs = (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId);

  const today = new Date();
  const todayRecords = records.filter(r=>new Date(r.learnDate).toDateString()===today.toDateString());
  const todayCount = todayRecords.length;
  const todayCorrect = todayRecords.filter(r=>r.correct).length;
  const todayAccuracy = todayCount>0 ? Math.round(todayCorrect/todayCount*100) : 0;
  const streak = computeStreak(records);
  const total = records.length;

  // 问候语
  const hour = today.getHours();
  let greeting = hour<6?'凌晨好':hour<12?'早上好':hour<14?'中午好':hour<18?'下午好':'晚上好';

  // 考研倒计时（12月21日）
  let examDate = new Date(today.getFullYear(),11,21);
  if(examDate < today) examDate = new Date(today.getFullYear()+1,11,21);
  const daysToExam = Math.ceil((examDate-today)/(1000*60*60*24));
  const examEl = document.getElementById('examCountdown');
  if(examEl) examEl.textContent = `距考研 ${daysToExam} 天`;

  // 复习任务
  const reviewTasks = await computeReviewTasks(records);
  // 薄弱知识点
  const weakPoints = computeWeakPoints(records);
  // 科目进度
  const subjectProgress = computeSubjectProgress(records);
  // 热力图
  const heatmap = computeHeatmap(records);

  let html = '';

  // 欢迎横幅
  html += `<div class="welcome-banner">
    <h2>${greeting}，${escapeHtml(currentUserName)}！${todayCount>0?'今天很棒，继续加油！':'今天还没开始刷题哦～'}</h2>
    <p>今天是 ${today.getFullYear()}年${today.getMonth()+1}月${today.getDate()}日 · ${'日一二三四五六'[today.getDay()]}曜日</p>
    <span class="date-tag">距考研还有 ${daysToExam} 天</span>
  </div>`;

  // 数据概览
  html += `<div class="stat-row" style="margin-bottom:1.2rem">
    <div class="stat-mini"><div class="sm-num">${todayCount}</div><div class="sm-label">今日刷题</div><div class="sm-delta ${todayCount>0?'up':''}">${todayCount>0?'+今天':'未开始'}</div></div>
    <div class="stat-mini"><div class="sm-num">${todayAccuracy}%</div><div class="sm-label">今日正确率</div><div class="sm-delta ${todayAccuracy>=60?'up':'down'}">${todayAccuracy>=60?'良好':'需努力'}</div></div>
    <div class="stat-mini"><div class="sm-num">${streak}</div><div class="sm-label">连续打卡</div><div class="sm-delta up">天</div></div>
    <div class="stat-mini"><div class="sm-num">${total}</div><div class="sm-label">累计刷题</div><div class="sm-delta up">${records.filter(r=>r.correct).length} 正确</div></div>
  </div>`;

  html += '<div class="dash-grid">';

  // 今日复习任务（左半）
  html += `<div class="dash-w-6"><div class="home-card">
    <div class="card-title">📅 今日复习任务（${MODES[currentMode].name}）<span class="card-more" onclick="switchPanel('quiz')">去刷题 →</span></div>`;
  if(reviewTasks.length===0){
    html += '<div class="empty-state" style="padding:1.5rem"><div class="es-icon">✅</div><p>暂无到期复习任务，开始学习新内容吧！</p></div>';
  } else {
    html += '<ul class="review-list">';
    reviewTasks.slice(0,6).forEach(t=>{
      const overdue = t.overdue;
      const dotColor = t.isErrorReview ? 'var(--red)' : (overdue?'var(--red)':'var(--yellow)');
      const tagClass = t.isErrorReview ? 'urgent' : (overdue?'urgent':'normal');
      const tagText = t.isErrorReview ? t.label : (overdue?'已逾期':'今日');
      html += `<li class="review-item">
        <span class="ri-dot" style="background:${dotColor}"></span>
        <span class="ri-title">${escapeHtml(t.title)} <span style="color:var(--muted);font-size:.72rem">· ${escapeHtml(t.label)}</span></span>
        <span class="ri-tag ${tagClass}">${tagText}</span>
      </li>`;
    });
    html += '</ul>';
  }
  html += '</div></div>';

  // 薄弱知识点（右半，与复习任务对称）
  html += `<div class="dash-w-6"><div class="home-card">
    <div class="card-title">🎯 薄弱知识点 TOP3</div>`;
  if(weakPoints.length===0){
    html += '<div class="empty-state" style="padding:1.5rem"><div class="es-icon">📊</div><p>暂无数据</p></div>';
  } else {
    html += '<ul class="weak-list">';
    weakPoints.forEach(w=>{
      const color = w.accuracy<50?'var(--red)':w.accuracy<80?'var(--yellow)':'var(--green)';
      html += `<li class="weak-item">
        <span style="font-size:.78rem;min-width:90px">${escapeHtml(w.chapter)}</span>
        <div class="weak-bar-bg"><div class="weak-bar-fill" style="width:${w.accuracy}%;background:${color}"></div></div>
        <span class="weak-pct">${w.accuracy}%</span>
      </li>`;
    });
    html += '</ul>';
  }
  html += '</div></div>';

  // 科目进度（全宽）
  html += `<div class="dash-w-12"><div class="home-card">
    <div class="card-title">📚 科目进度</div>
    <div class="subject-grid">`;
  subjectProgress.forEach(s=>{
    const pct = s.total>0 ? Math.round(s.done/s.total*100) : 0;
    html += `<div class="subject-card" onclick="switchPanel('quiz')">
      <div class="sub-name">${s.icon} ${s.name}</div>
      <div class="sub-meta"><span>${s.done}/${s.total}题</span><span>正确率 ${s.accuracy}%</span></div>
      <div class="sub-progress-wrap"><div class="sub-progress-fill" style="width:${pct}%;background:${s.accuracy>=60?'var(--green)':'var(--accent)'}"></div></div>
    </div>`;
  });
  html += '</div></div></div>';

  // 学习热力图（全宽）
  html += `<div class="dash-w-12"><div class="home-card">
    <div class="card-title">🔥 近14天学习热力图</div>
    <div class="heatmap-row" style="margin-bottom:.5rem">`;
  heatmap.forEach(d=>{
    let bg='var(--bg2)';
    if(d.count>=6) bg='var(--accent)';
    else if(d.count>=3) bg='var(--accent2)';
    else if(d.count>=1) bg='var(--accent-light)';
    const title=`${d.date.getMonth()+1}/${d.date.getDate()}: ${d.count}题`;
    html += `<div class="heatmap-cell" title="${title}" style="background:${bg}"></div>`;
  });
  html += '</div>';
  html += '<div style="display:flex;align-items:center;gap:.6rem;font-size:.72rem;color:var(--muted)"><span>少</span>';
  html += '<div class="heatmap-cell" style="background:var(--bg2)"></div>';
  html += '<div class="heatmap-cell" style="background:var(--accent-light)"></div>';
  html += '<div class="heatmap-cell" style="background:var(--accent2)"></div>';
  html += '<div class="heatmap-cell" style="background:var(--accent)"></div>';
  html += '<span>多</span></div>';
  html += '</div></div>';

  html += '</div>'; // dash-grid end

  el.innerHTML = html;
}

function renderEbbinghausNodes(mode){
  return '';
}

function computeStreak(records){
  if(records.length===0) return 0;
  const days = new Set(records.map(r=>new Date(r.learnDate).toDateString()));
  let streak=0;
  const d = new Date(); d.setHours(0,0,0,0);
  // 如果今天没有记录，从昨天开始算
  if(!days.has(d.toDateString())) d.setDate(d.getDate()-1);
  while(days.has(d.toDateString())){
    streak++;
    d.setDate(d.getDate()-1);
  }
  return streak;
}

async function computeReviewTasks(records){
  const mode = MODES[currentMode];
  const tasks = [];
  
  if(mode.isErrorMode){
    // 仅错题复习模式：返回所有错题作为复习任务
    const wrongQs = (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId);
    wrongQs.forEach(w=>{
      tasks.push({ qid:w.questionId, title:w.title, subject:w.subject, chapter:w.chapter, label:`错${w.wrongCount}次`, node:0, overdue:false, isErrorReview:true });
    });
    return tasks;
  }
  
  // 极简模式：按时间节点计算
  const byQuestion = {};
  records.forEach(r=>{
    if(!byQuestion[r.questionId]) byQuestion[r.questionId] = { title:r.title, subject:r.subject, chapter:r.chapter, dates:[] };
    byQuestion[r.questionId].dates.push(new Date(r.learnDate));
  });
  const today = new Date(); today.setHours(0,0,0,0);
  Object.entries(byQuestion).forEach(([qid,data])=>{
    const firstLearn = new Date(Math.min(...data.dates.map(d=>d.getTime())));
    firstLearn.setHours(0,0,0,0);
    for(let i=0;i<mode.nodes.length;i++){
      const reviewDate = new Date(firstLearn);
      reviewDate.setDate(reviewDate.getDate()+mode.nodes[i]);
      const reviewed = data.dates.some(d=>{ const dd=new Date(d); dd.setHours(0,0,0,0); return dd.getTime()>=reviewDate.getTime(); });
      if(!reviewed && reviewDate<=today){
        tasks.push({ qid, title:data.title, subject:data.subject, chapter:data.chapter, label:`第${mode.nodes[i]}天`, node:mode.nodes[i], overdue: reviewDate<today });
        break;
      }
    }
  });
  tasks.sort((a,b)=>(b.overdue?1:0)-(a.overdue?1:0));
  return tasks;
}

function computeWeakPoints(records){
  const byChapter = {};
  records.forEach(r=>{
    const key = r.chapter;
    if(!byChapter[key]) byChapter[key] = { chapter:r.chapter, subject:r.subject, total:0, correct:0 };
    byChapter[key].total++;
    if(r.correct) byChapter[key].correct++;
  });
  return Object.values(byChapter)
    .map(c=>({...c, accuracy:c.total>0?Math.round(c.correct/c.total*100):0}))
    .sort((a,b)=>a.accuracy-b.accuracy)
    .slice(0,3);
}

function computeSubjectProgress(records){
  const result = [];
  Object.entries(SUBJECTS).forEach(([key,sub])=>{
    const subRecords = records.filter(r=>r.subject===key);
    const doneSet = new Set(subRecords.map(r=>r.questionId));
    const totalQuestions = allQuestions.filter(q=>q.subject===key).length;
    const correct = subRecords.filter(r=>r.correct).length;
    const accuracy = subRecords.length>0 ? Math.round(correct/subRecords.length*100) : 0;
    result.push({ key, name:sub.name, icon:sub.icon, done:doneSet.size, total:totalQuestions, accuracy });
  });
  return result;
}

function computeHeatmap(records){
  const days = [];
  const today = new Date(); today.setHours(0,0,0,0);
  for(let i=13;i>=0;i--){
    const d = new Date(today); d.setDate(d.getDate()-i);
    const count = records.filter(r=>new Date(r.learnDate).toDateString()===d.toDateString()).length;
    days.push({ date:d, count });
  }
  return days;
}

function selectMode(mode){
  currentMode = mode;
  saveUserSetting('mode', mode);
  // 更新模式选择器UI
  document.querySelectorAll('.mode-card').forEach((card,i)=>{
    const keys = Object.keys(MODES);
    card.classList.toggle('active', keys[i]===mode);
    const badge = card.querySelector('.mc-badge');
    if(keys[i]===mode && !badge){
      const b=document.createElement('div'); b.className='mc-badge'; b.textContent='当前'; card.appendChild(b);
    } else if(keys[i]!==mode && badge){
      badge.remove();
    }
  });
}

function updateEbbinghausDisplay(mode){
  // 复习节点板块已删除，此函数保留为空避免报错
}

/* ==========================================================
 * 3.8 错题本
 * ========================================================== */
async function renderWrong(){
  const el = document.getElementById('wrongContent');
  let wrongQs = (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId);

  let filterHtml = '<div class="filter-bar">';
  filterHtml += `<button class="filter-pill ${wrongFilterSubject==='all'?'active':''}" onclick="setWrongFilter('all')">全部</button>`;
  Object.entries(SUBJECTS).forEach(([key,sub])=>{
    const has = wrongQs.some(w=>w.subject===key);
    if(has){
      filterHtml += `<button class="filter-pill ${wrongFilterSubject===key?'active':''}" onclick="setWrongFilter('${key}')">${sub.icon} ${sub.name}</button>`;
    }
  });
  filterHtml += '</div>';

  if(wrongFilterSubject!=='all'){
    wrongQs = wrongQs.filter(w=>w.subject===wrongFilterSubject);
  }

  let listHtml = '';
  if(wrongQs.length===0){
    listHtml = '<div class="empty-state"><div class="es-icon">🎉</div><p>错题本为空，继续保持！</p></div>';
  } else {
    wrongQs.sort((a,b)=>new Date(b.lastWrongDate)-new Date(a.lastWrongDate));
    listHtml = wrongQs.map(w=>{
      const sub = SUBJECTS[w.subject] || {icon:'📝',name:'未知'};
      const fav = favoritedIds.has(w.questionId);
      return `<div class="error-card">
        <div class="ec-icon">${sub.icon}</div>
        <div class="ec-body">
          <div class="ec-title">${escapeHtml(w.title)}</div>
          <div class="ec-meta">${sub.name} · 最近：${formatDate(w.lastWrongDate)}</div>
          <div style="display:flex;gap:.3rem;margin-top:.3rem">
            <span style="background:var(--red-bg);color:var(--red);padding:.1rem .4rem;border-radius:4px;font-size:.65rem;font-weight:600">❌ ${w.wrongCount}次</span>
            <span style="background:var(--green-bg);color:var(--green);padding:.1rem .4rem;border-radius:4px;font-size:.65rem;font-weight:600">✅ ${w.correctCount||0}次</span>
          </div>
        </div>
        <div class="ec-actions">
          <button onclick="redoWrong('${w.questionId}')">重做</button>
          <button onclick="openNoteModal('${w.questionId}')">解析</button>
        </div>
      </div>`;
    }).join('');
  }

  el.innerHTML = `<h3 style="font-size:1rem;margin-bottom:1rem">❌ 错题本（共 ${wrongQs.length} 题）</h3>` + filterHtml + listHtml;
}

function setWrongFilter(subject){
  wrongFilterSubject = subject;
  renderWrong();
}

async function redoWrong(questionId){
  const w = await dbGetByKey('wrongQuestions', `wq_${currentUserId}_${questionId}`);
  if(!w || !w.question){
    alert('未找到该错题');
    return;
  }
  currentQuestions = [w.question];
  currentQuestionIndex = 0;
  const favs = (await dbGetAll('favorites')).filter(f=>f.userId===currentUserId);
  favoritedIds = new Set(favs.map(f=>f.questionId));
  switchPanel('quiz');
  renderQuestion();
}

/* ==========================================================
 * 3.9 学习统计
 * ========================================================== */
async function renderStats(){
  const el = document.getElementById('statsContent');
  const records = (await dbGetAll('records')).filter(r=>r.userId===currentUserId);
  const wrongQs = (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId);

  // 7天柱状图
  const today = new Date(); today.setHours(0,0,0,0);
  const days = [];
  for(let i=6;i>=0;i--){
    const d = new Date(today); d.setDate(d.getDate()-i);
    const dayRecords = records.filter(r=>new Date(r.learnDate).toDateString()===d.toDateString());
    const correct = dayRecords.filter(r=>r.correct).length;
    const accuracy = dayRecords.length>0 ? Math.round(correct/dayRecords.length*100) : 0;
    days.push({ date:d, count:dayRecords.length, accuracy });
  }
  const maxCount = Math.max(...days.map(d=>d.count),1);

  let barHtml = '<div class="simple-bar">';
  days.forEach(d=>{
    const h = d.count>0 ? Math.round(d.count/maxCount*100) : 4;
    const color = d.count===0?'var(--bg3)':d.accuracy>=80?'var(--green)':d.accuracy>=50?'var(--yellow)':'var(--red)';
    barHtml += `<div class="bar-col">
      <div style="font-size:.65rem;color:var(--muted);margin-bottom:2px">${d.count||''}</div>
      <div class="bar-fill" style="height:${h}%;background:${color}"></div>
      <div class="bar-label">${d.date.getMonth()+1}/${d.date.getDate()}</div>
    </div>`;
  });
  barHtml += '</div>';

  // 科目能力概览
  const subjectProgress = computeSubjectProgress(records);
  let abilityHtml = '<div style="display:grid;grid-template-columns:1fr 1fr;gap:.8rem">';
  subjectProgress.forEach(s=>{
    if(s.total===0) return;
    const level = s.accuracy>=80?'优秀':s.accuracy>=60?'良好':s.accuracy>=40?'一般':'薄弱';
    const color = s.accuracy>=80?'var(--green)':s.accuracy>=60?'var(--blue)':s.accuracy>=40?'var(--yellow)':'var(--red)';
    abilityHtml += `<div style="padding:.8rem;border-radius:8px;background:var(--bg2);border-left:3px solid ${color}">
      <div style="font-size:.85rem;font-weight:600">${s.icon} ${s.name}</div>
      <div style="font-size:.78rem;color:var(--muted);margin-top:.2rem">正确率 ${s.accuracy}% · ${level}</div>
    </div>`;
  });
  abilityHtml += '</div>';

  // 科目明细表
  let tableHtml = `<div class="table-wrap" style="margin-top:1rem"><table class="deploy-table" style="width:100%;border-collapse:collapse;font-size:.8rem">
    <thead><tr>
      <th style="text-align:left;padding:.5rem;background:var(--bg2);border-bottom:2px solid var(--rule)">科目</th>
      <th style="padding:.5rem;background:var(--bg2)">题库</th>
      <th style="padding:.5rem;background:var(--bg2)">已做</th>
      <th style="padding:.5rem;background:var(--bg2)">完成率</th>
      <th style="padding:.5rem;background:var(--bg2)">正确率</th>
      <th style="padding:.5rem;background:var(--bg2)">错题</th>
      <th style="text-align:left;padding:.5rem;background:var(--bg2)">薄弱章节</th>
    </tr></thead><tbody>`;
  subjectProgress.forEach(s=>{
    const subWrong = wrongQs.filter(w=>w.subject===s.key);
    const weak = computeWeakPoints(records.filter(r=>r.subject===s.key));
    const completion = s.total>0?Math.round(s.done/s.total*100):0;
    tableHtml += `<tr>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule)">${s.icon} ${s.name}</td>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule);text-align:center">${s.total}</td>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule);text-align:center">${s.done}</td>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule);text-align:center">${completion}%</td>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule);text-align:center;color:${s.accuracy>=60?'var(--green)':'var(--red)'}">${s.accuracy}%</td>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule);text-align:center">${subWrong.length}</td>
      <td style="padding:.5rem;border-bottom:1px solid var(--rule);color:var(--muted)">${weak.length>0?escapeHtml(weak[0].chapter):'—'}</td>
    </tr>`;
  });
  tableHtml += '</tbody></table></div>';

  // 题目对错次数统计
  const byQuestion = {};
  records.forEach(r=>{
    if(!byQuestion[r.questionId]) byQuestion[r.questionId] = { title:r.title, subject:r.subject, correct:0, wrong:0, total:0 };
    byQuestion[r.questionId].total++;
    if(r.correct) byQuestion[r.questionId].correct++;
    else byQuestion[r.questionId].wrong++;
  });
  const questionStats = Object.values(byQuestion).sort((a,b)=>b.wrong-a.wrong);
  let qStatsHtml = `<div class="table-wrap" style="margin-top:1rem"><table class="deploy-table" style="width:100%;border-collapse:collapse;font-size:.8rem">
    <thead><tr>
      <th style="text-align:left;padding:.5rem;background:var(--bg2);border-bottom:2px solid var(--rule)">题目</th>
      <th style="padding:.5rem;background:var(--bg2)">✅ 正确</th>
      <th style="padding:.5rem;background:var(--bg2)">❌ 错误</th>
      <th style="padding:.5rem;background:var(--bg2)">正确率</th>
    </tr></thead><tbody>`;
  questionStats.forEach(qs=>{
    const acc = qs.total>0 ? Math.round(qs.correct/qs.total*100) : 0;
    qStatsHtml += `<tr>
      <td style="padding:.4rem .5rem;border-bottom:1px solid var(--rule)">${escapeHtml(qs.title)}</td>
      <td style="text-align:center;padding:.4rem;border-bottom:1px solid var(--rule);color:var(--green)">${qs.correct}</td>
      <td style="text-align:center;padding:.4rem;border-bottom:1px solid var(--rule);color:var(--red)">${qs.wrong}</td>
      <td style="text-align:center;padding:.4rem;border-bottom:1px solid var(--rule);color:${acc>=60?'var(--green)':'var(--red)'}">${acc}%</td>
    </tr>`;
  });
  qStatsHtml += '</tbody></table></div>';

  el.innerHTML = `
    <div class="chart-card">
      <div class="chart-title">📊 近7天刷题量（颜色代表正确率）</div>
      ${barHtml}
    </div>
    <div class="chart-card">
      <div class="chart-title">💪 科目能力概览</div>
      ${abilityHtml}
    </div>
    <div class="chart-card">
      <div class="chart-title">📋 科目明细</div>
      ${tableHtml}
    </div>
    <div class="chart-card">
      <div class="chart-title">📝 题目对错次数</div>
      ${qStatsHtml}
    </div>`;
}

/* ==========================================================
 * 3.10 收藏夹
 * ========================================================== */
async function renderFavorites(){
  const el = document.getElementById('favContent');
  const favs = (await dbGetAll('favorites')).filter(f=>f.userId===currentUserId);
  favoritedIds = new Set(favs.map(f=>f.questionId));
  let html = `<h3 style="font-size:1rem;margin-bottom:1rem">⭐ 收藏夹（共 ${favs.length} 题）</h3>`;
  if(favs.length===0){
    html += '<div class="empty-state"><div class="es-icon">⭐</div><p>还没有收藏的题目</p></div>';
  } else {
    favs.sort((a,b)=>new Date(b.addedDate)-new Date(a.addedDate));
    favs.forEach(f=>{
      const sub = SUBJECTS[f.subject] || {icon:'📝',name:'未知'};
      html += `<div class="error-card">
        <div class="ec-icon">${sub.icon}</div>
        <div class="ec-body">
          <div class="ec-title">${escapeHtml(f.title)}</div>
          <div class="ec-meta">${sub.name} · ${escapeHtml(f.chapter||'')} · 收藏于 ${formatDate(f.addedDate)}</div>
        </div>
        <div class="ec-actions">
          <button onclick="redoFavorite('${f.questionId}')">练习</button>
          <button onclick="removeFavorite('${f.questionId}')">取消</button>
        </div>
      </div>`;
    });
  }
  el.innerHTML = html;
}

async function redoFavorite(questionId){
  const fav = await dbGetByKey('favorites', `fav_${currentUserId}_${questionId}`);
  if(!fav || !fav.question){
    alert('未找到该题目');
    return;
  }
  currentQuestions = [fav.question];
  currentQuestionIndex = 0;
  switchPanel('quiz');
  renderQuestion();
}

async function removeFavorite(questionId){
  await dbDelete('favorites', `fav_${currentUserId}_${questionId}`);
  favoritedIds.delete(questionId);
  renderFavorites();
}

/* ==========================================================
 * 3.11 我的解析
 * ========================================================== */
async function renderNotes(){
  const el = document.getElementById('notesContent');
  let notes = (await dbGetAll('notes')).filter(n=>n.userId===currentUserId);

  let html = `<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;flex-wrap:wrap;gap:.5rem">
    <h3 style="font-size:1rem">📋 我的解析（共 ${notes.length} 条）</h3>
    <div style="display:flex;gap:.5rem">
      <button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="exportNotes()">📥 导出</button>
      <button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="document.getElementById('noteImportInput').click()">📤 导入</button>
      <input type="file" id="noteImportInput" accept=".json" style="display:none" onchange="importNotes(event)">
    </div>
  </div>`;

  // 过滤栏
  html += '<div class="filter-bar">';
  html += `<button class="filter-pill ${noteFilterSubject==='all'?'active':''}" onclick="setNoteFilter('all')">全部</button>`;
  Object.entries(SUBJECTS).forEach(([key,sub])=>{
    const has = notes.some(n=>n.subject===key);
    if(has) html += `<button class="filter-pill ${noteFilterSubject===key?'active':''}" onclick="setNoteFilter('${key}')">${sub.icon} ${sub.name}</button>`;
  });
  html += '</div>';

  if(noteFilterSubject!=='all'){
    notes = notes.filter(n=>n.subject===noteFilterSubject);
  }

  if(notes.length===0){
    html += '<div class="empty-state"><div class="es-icon">📋</div><p>还没有添加解析笔记，刷题时点击"添加解析"即可记录</p></div>';
  } else {
    notes.sort((a,b)=>new Date(b.createdDate)-new Date(a.createdDate));
    notes.forEach(n=>{
      const sub = SUBJECTS[n.subject] || {icon:'📝',name:'未知'};
      let imgs = '';
      if(n.images && n.images.length>0){
        imgs = '<div class="nc-images">'+n.images.map(src=>`<div class="nc-thumb" onclick="window.open('${src}')"><img src="${src}" style="width:100%;height:100%;object-fit:cover"></div>`).join('')+'</div>';
      }
      html += `<div class="note-card">
        <div class="nc-header">
          <span class="tag tag-blue">${sub.icon} ${sub.name}</span>
          <span style="font-size:.72rem;color:var(--muted)">${escapeHtml(n.chapter||'')}</span>
          <span class="nc-title">${escapeHtml(n.title)}</span>
        </div>
        ${n.text?`<div style="font-size:.85rem;line-height:1.7;white-space:pre-wrap">${escapeHtml(n.text)}</div>`:''}
        ${imgs}
        <div style="font-size:.72rem;color:var(--muted);margin-top:.4rem">📅 ${formatDate(n.createdDate)}</div>
        <div class="nc-actions">
          <button class="btn-sm" onclick="editNote('${n.id}')">编辑</button>
          <button class="btn-sm" onclick="deleteNote('${n.id}')">删除</button>
        </div>
      </div>`;
    });
  }
  el.innerHTML = html;
}

function setNoteFilter(subject){
  noteFilterSubject = subject;
  renderNotes();
}

function openNoteModal(questionId){
  currentNoteTarget = questionId;
  const q = allQuestions.find(q=>q.id===questionId);
  document.getElementById('noteTarget').textContent = '题目：'+(q?q.title:questionId);
  document.getElementById('noteText').value = '';
  currentNoteImages = [];
  document.getElementById('noteImagePreview').innerHTML = '';
  document.getElementById('noteModal').classList.add('show');
}

function closeNoteModal(){
  document.getElementById('noteModal').classList.remove('show');
}

function previewNoteImages(event){
  const files = Array.from(event.target.files);
  files.forEach(file=>{
    const reader = new FileReader();
    reader.onload = (e)=>{
      currentNoteImages.push(e.target.result);
      const img = document.createElement('img');
      img.src = e.target.result;
      document.getElementById('noteImagePreview').appendChild(img);
    };
    reader.readAsDataURL(file);
  });
}

async function saveNote(){
  const text = document.getElementById('noteText').value.trim();
  if(!text && currentNoteImages.length===0){
    alert('请输入解析内容或上传图片');
    return;
  }
  const q = allQuestions.find(q=>q.id===currentNoteTarget);
  const id = `note_${currentUserId}_${currentNoteTarget}_${Date.now()}`;
  await dbAdd('notes', {
    id, userId:currentUserId, questionId:currentNoteTarget,
    subject:q?q.subject:'', system:q?q.system:'', chapter:q?q.chapter:'',
    title:q?q.title:currentNoteTarget,
    text, images:currentNoteImages, createdDate:new Date().toISOString()
  });
  closeNoteModal();
  // 如果当前在解析页则刷新
  if(document.getElementById('panel-notes').classList.contains('active')) renderNotes();
}

async function editNote(noteId){
  const note = await dbGetByKey('notes', noteId);
  if(!note) return;
  currentNoteTarget = note.questionId;
  document.getElementById('noteTarget').textContent = '题目：'+note.title;
  document.getElementById('noteText').value = note.text||'';
  currentNoteImages = note.images||[];
  const preview = document.getElementById('noteImagePreview');
  preview.innerHTML = '';
  currentNoteImages.forEach(src=>{ const img=document.createElement('img'); img.src=src; preview.appendChild(img); });
  document.getElementById('noteModal').classList.add('show');
  // 改保存按钮行为为更新
  document.querySelector('.btn-save').onclick = async ()=>{
    const newText = document.getElementById('noteText').value.trim();
    note.text = newText;
    note.images = currentNoteImages;
    await dbAdd('notes', note);
    closeNoteModal();
    document.querySelector('.btn-save').onclick = saveNote;
    renderNotes();
  };
}

async function deleteNote(noteId){
  if(!confirm('确定删除该解析？')) return;
  await dbDelete('notes', noteId);
  renderNotes();
}

/* ==========================================================
 * 3.12 设置
 * ========================================================== */
async function renderSettings(){
  const el = document.getElementById('settingsContent');
  const token = localStorage.getItem('xuecheng_gist_token')||'';
  const gistId = localStorage.getItem('xuecheng_gist_id')||'';
  const gistIdDisplay = gistId ? gistId.substring(0,8)+'...' : '未创建';
  const syncStatus = gistId ? '已关联 Gist' : '未关联';

  let html = '';

  // 复习模式
  html += `<div class="home-card" style="margin-bottom:1.2rem">
    <div class="card-title">🔄 复习模式选择</div>
    <div class="mode-selector">`;
  Object.entries(MODES).forEach(([key,m])=>{
    const nodesText = m.isErrorMode ? '无时间限制' : m.nodes.join(' → ') + ' 天';
    html += `<div class="mode-card ${key===currentMode?'active':''}" onclick="selectMode('${key}');renderSettings()">
      <div class="mc-title">${m.name}</div>
      <div class="mc-nodes">${nodesText}</div>
      ${key===currentMode?'<div class="mc-badge">当前</div>':''}
    </div>`;
  });
  html += '</div></div>';

  // 偏好设置
  html += `<div class="home-card" style="margin-bottom:1.2rem">
    <div class="card-title">⚙️ 偏好设置</div>
    <div class="setting-row">
      <div class="setting-label">🔀 打乱选项顺序<div class="sl-desc">每次刷题时随机打乱选项排列，强化记忆</div></div>
      <div class="setting-control">
        <div class="toggle ${shuffleOptionsEnabled?'on':''}" data-toggle="shuffle" onclick="toggleShuffleOptions()"></div>
      </div>
    </div>
    <div class="setting-row">
      <div class="setting-label">🌙 深色模式<div class="sl-desc">切换到深色主题，护眼夜间使用</div></div>
      <div class="setting-control">
        <div class="toggle ${darkModeEnabled?'on':''}" data-toggle="darkMode" onclick="toggleDarkMode()"></div>
      </div>
    </div>
  </div>`;

  // 云同步
  html += `<div class="home-card" style="margin-bottom:1.2rem">
    <div class="card-title">☁️ 云同步（GitHub Gist）</div>
    <div class="setting-row">
      <div class="setting-label">GitHub Token<div class="sl-desc">用于访问 Gist API（仅本地存储）</div></div>
      <div class="setting-control">
        <input type="password" id="gistTokenInput" placeholder="ghp_xxx..." value="${escapeHtml(token)}" style="padding:.4rem .6rem;border-radius:6px;border:1px solid var(--rule);font-size:.78rem;width:180px;font-family:var(--font)">
        <button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="saveToken()">保存</button>
      </div>
    </div>
    <div class="setting-row">
      <div class="setting-label">同步状态<div class="sl-desc">Gist ID: ${escapeHtml(gistIdDisplay)}</div></div>
      <div class="setting-control" style="font-size:.78rem;color:${gistId?'var(--green)':'var(--muted)'}">${syncStatus}</div>
    </div>
    <div class="setting-row">
      <div class="setting-label">手动同步<div class="sl-desc">上传当前数据到云端 / 从云端拉取</div></div>
      <div class="setting-control">
        <button class="btn btn-primary" style="font-size:.78rem;padding:.4rem .8rem" onclick="syncToCloud().then(()=>alert('上传成功')).catch(e=>alert('上传失败: '+e.message))">⬆️ 上传</button>
        <button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="syncFromCloud().then(()=>alert('下载成功，已合并')).catch(e=>alert('下载失败: '+e.message))">⬇️ 下载</button>
      </div>
    </div>
    <div class="setting-row">
      <div class="setting-label">自动同步<div class="sl-desc">每次刷题后自动上传</div></div>
      <div class="setting-control">
        <div class="toggle ${autoSyncEnabled?'on':''}" onclick="toggleAutoSync()"></div>
      </div>
    </div>
    <div style="font-size:.72rem;color:var(--muted);margin-top:.6rem;line-height:1.6">
      💡 获取 Token：GitHub → Settings → Developer settings → Personal access tokens → 勾选 <strong>gist</strong> 权限。数据以私有 Gist 存储，仅你自己可访问。
    </div>
  </div>`;

  // 数据管理
  html += `<div class="home-card" style="margin-bottom:1.2rem">
    <div class="card-title">💾 数据管理</div>
    <div class="setting-row">
      <div class="setting-label">导出解析笔记<div class="sl-desc">导出为 JSON 文件</div></div>
      <div class="setting-control"><button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="exportNotes()">📥 导出笔记</button></div>
    </div>
    <div class="setting-row">
      <div class="setting-label">导入解析笔记<div class="sl-desc">从 JSON 文件导入</div></div>
      <div class="setting-control"><button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="document.getElementById('settingsNoteImport').click()">📤 导入笔记</button>
      <input type="file" id="settingsNoteImport" accept=".json" style="display:none" onchange="importNotes(event)"></div>
    </div>
    <div class="setting-row">
      <div class="setting-label">导出全部数据<div class="sl-desc">备份所有刷题记录、错题、收藏、笔记</div></div>
      <div class="setting-control"><button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="exportAllData()">📥 全部备份</button></div>
    </div>
    <div class="setting-row">
      <div class="setting-label">清空全部数据<div class="sl-desc">清除当前用户所有 IndexedDB 数据（不可恢复）</div></div>
      <div class="setting-control"><button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem;color:var(--red);border-color:var(--red)" onclick="clearAllData()">🗑️ 清空</button></div>
    </div>
  </div>`;

  // 题目导入
  html += `<div class="home-card">
    <div class="card-title">📥 题目导入</div>
    <div class="setting-row">
      <div class="setting-label">导入自定义题目<div class="sl-desc">从 JSON 文件导入匹配题，格式见说明</div></div>
      <div class="setting-control"><button class="btn btn-outline" style="font-size:.78rem;padding:.4rem .8rem" onclick="document.getElementById('questionImportInput').click()">选择文件</button>
      <input type="file" id="questionImportInput" accept=".json" style="display:none" onchange="importQuestions(event)"></div>
    </div>
    <div style="font-size:.72rem;color:var(--muted);margin-top:.6rem;line-height:1.6">
      JSON 格式为题目数组，每题包含 id、subject、system、chapter、type、title、description、options、categories、answer、explanation 字段。
    </div>
  </div>`;

  el.innerHTML = html;
}

/* ==========================================================
 * 3.13 云同步（GitHub Gist）
 * ========================================================== */
function saveToken(){
  const token = document.getElementById('gistTokenInput').value.trim();
  if(token){
    localStorage.setItem('xuecheng_gist_token', token);
    alert('Token 已保存');
  } else {
    localStorage.removeItem('xuecheng_gist_token');
    alert('Token 已清除');
  }
  renderSettings();
}

async function syncToCloud(){
  const token = localStorage.getItem('xuecheng_gist_token');
  if(!token) throw new Error('请先输入并保存 GitHub Token');
  const data = {
    records: await dbGetAll('records'),
    wrongQuestions: await dbGetAll('wrongQuestions'),
    favorites: await dbGetAll('favorites'),
    notes: await dbGetAll('notes'),
    users: await dbGetAll('users'),
    questions: await dbGetAll('questions'),
    syncTime: new Date().toISOString()
  };
  const content = JSON.stringify(data, null, 2);
  const gistId = localStorage.getItem('xuecheng_gist_id');
  const url = gistId ? `https://api.github.com/gists/${gistId}` : 'https://api.github.com/gists';
  const method = gistId ? 'PATCH' : 'POST';
  const res = await fetch(url, {
    method,
    headers: {
      'Authorization': `token ${token}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github.v3+json'
    },
    body: JSON.stringify({
      description: '学成选择题数据备份',
      public: false,
      files: { 'xuecheng_backup.json': { content } }
    })
  });
  if(!res.ok){
    const err = await res.json().catch(()=>({}));
    throw new Error(err.message || `HTTP ${res.status}`);
  }
  const gist = await res.json();
  if(!gistId){
    localStorage.setItem('xuecheng_gist_id', gist.id);
  }
}

async function syncFromCloud(){
  const token = localStorage.getItem('xuecheng_gist_token');
  const gistId = localStorage.getItem('xuecheng_gist_id');
  if(!token) throw new Error('请先输入并保存 GitHub Token');
  if(!gistId) throw new Error('请先上传一次以创建 Gist');
  const res = await fetch(`https://api.github.com/gists/${gistId}`, {
    headers: { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' }
  });
  if(!res.ok){
    const err = await res.json().catch(()=>({}));
    throw new Error(err.message || `HTTP ${res.status}`);
  }
  const gist = await res.json();
  const file = gist.files && gist.files['xuecheng_backup.json'];
  if(!file || !file.content) throw new Error('云端未找到备份数据');
  const data = JSON.parse(file.content);
  for(const store of ['records','wrongQuestions','favorites','notes','users','questions']){
    if(data[store] && Array.isArray(data[store])){
      for(const item of data[store]){
        if(item && item.id) await dbAdd(store, item);
      }
    }
  }
  // 重新加载题目
  await reloadQuestions();
  await updateWrongBadge();
  await updateUserStreak();
  renderSettings();
}

async function quickSync(){
  const token = localStorage.getItem('xuecheng_gist_token');
  if(!token){
    alert('请先在设置中配置 GitHub Token');
    switchPanel('settings');
    return;
  }
  try{
    await syncToCloud();
    alert('☁️ 同步上传成功！');
  }catch(e){
    alert('同步失败：'+e.message);
  }
}

function toggleAutoSync(){
  autoSyncEnabled = !autoSyncEnabled;
  saveUserSetting('autoSync', autoSyncEnabled);
  const t = document.querySelector('.home-card .toggle');
  if(t) t.classList.toggle('on', autoSyncEnabled);
}

function toggleShuffleOptions(){
  shuffleOptionsEnabled = !shuffleOptionsEnabled;
  saveUserSetting('shuffleOptions', shuffleOptionsEnabled);
  const toggles = document.querySelectorAll('[data-toggle="shuffle"]');
  toggles.forEach(t=>t.classList.toggle('on', shuffleOptionsEnabled));
}

function toggleDarkMode(){
  darkModeEnabled = !darkModeEnabled;
  saveUserSetting('darkMode', darkModeEnabled);
  applyDarkMode();
  const toggles = document.querySelectorAll('[data-toggle="darkMode"]');
  toggles.forEach(t=>t.classList.toggle('on', darkModeEnabled));
}

function applyDarkMode(){
  if(darkModeEnabled){
    document.documentElement.classList.add('dark-mode');
  } else {
    document.documentElement.classList.remove('dark-mode');
  }
}

/* ==========================================================
 * 3.14 用户管理
 * ========================================================== */
async function toggleUserDropdown(){
  const dd = document.getElementById('userDropdown');
  if(dd.classList.contains('show')){
    dd.classList.remove('show');
    return;
  }
  const users = await dbGetAll('users');
  let html = users.map(u=>`
    <button class="ud-item ${u.id===currentUserId?'active':''}" onclick="switchUser(${u.id})">
      <div class="ud-avatar" style="background:${userColor(u.id)}">${escapeHtml(u.name.charAt(0).toUpperCase())}</div>
      ${escapeHtml(u.name)}
      ${u.id===currentUserId?'<span style="margin-left:auto">✓</span>':''}
    </button>
  `).join('');
  html += `<div class="ud-divider"></div><button class="ud-add" onclick="addNewUser()">+ 添加新用户</button>`;
  dd.innerHTML = html;
  dd.classList.add('show');
}

async function switchUser(userId){
  currentUserId = userId;
  const user = await dbGetByKey('users', userId);
  if(user) currentUserName = user.name;
  document.getElementById('userDropdown').classList.remove('show');
  // 加载用户设置
  await loadUserSettings();
  await updateUserDisplay();
  await updateWrongBadge();
  switchPanel('home');
}

async function addNewUser(){
  const name = prompt('请输入新用户名：');
  if(!name || !name.trim()) return;
  const users = await dbGetAll('users');
  const newId = users.length>0 ? Math.max(...users.map(u=>u.id))+1 : 1;
  await dbAdd('users', { id:newId, name:name.trim(), createdDate:new Date().toISOString() });
  await switchUser(newId);
}

async function updateUserDisplay(){
  const avatar = document.getElementById('currentUserAvatar');
  const nameEl = document.getElementById('currentUserName');
  if(avatar){
    avatar.textContent = currentUserName.charAt(0).toUpperCase();
    avatar.style.background = userColor(currentUserId);
  }
  if(nameEl) nameEl.textContent = currentUserName;
  await updateUserStreak();
}

async function updateUserStreak(){
  const records = (await dbGetAll('records')).filter(r=>r.userId===currentUserId);
  const streak = computeStreak(records);
  const el = document.getElementById('userStreak');
  if(el) el.textContent = `连续打卡 ${streak} 天`;
}

async function updateWrongBadge(){
  const wrongQs = (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId);
  const badge = document.getElementById('wrongBadge');
  if(badge) badge.textContent = wrongQs.length;
}

/* ==========================================================
 * 用户设置存取
 * ========================================================== */
async function saveUserSetting(key, value){
  const id = `settings_${currentUserId}`;
  let settings = await dbGetByKey('settings', id);
  if(!settings){ settings = { id, userId:currentUserId }; }
  settings[key] = value;
  await dbAdd('settings', settings);
}

async function loadUserSettings(){
  const settings = await dbGetByKey('settings', `settings_${currentUserId}`);
  if(settings){
    if(settings.mode) currentMode = settings.mode;
    if(typeof settings.autoSync === 'boolean') autoSyncEnabled = settings.autoSync;
    if(typeof settings.shuffleOptions === 'boolean') shuffleOptionsEnabled = settings.shuffleOptions;
    if(typeof settings.darkMode === 'boolean') darkModeEnabled = settings.darkMode;
  }
  applyDarkMode();
}

/* ==========================================================
 * 3.16 数据导入/导出
 * ========================================================== */
async function exportNotes(){
  const notes = (await dbGetAll('notes')).filter(n=>n.userId===currentUserId);
  if(notes.length===0){ alert('暂无解析笔记可导出'); return; }
  const blob = new Blob([JSON.stringify(notes, null, 2)], { type:'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `xuecheng_notes_${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(a.href);
}

async function importNotes(event){
  const file = event.target.files[0];
  if(!file) return;
  try{
    const text = await file.text();
    const data = JSON.parse(text);
    const arr = Array.isArray(data) ? data : [data];
    let count = 0;
    for(const n of arr){
      if(!n.id) n.id = `note_${currentUserId}_${n.questionId||'unknown'}_${Date.now()}_${count}`;
      n.userId = currentUserId;
      await dbAdd('notes', n);
      count++;
    }
    alert(`成功导入 ${count} 条笔记`);
    renderNotes();
  }catch(e){
    alert('导入失败：'+e.message);
  }
  event.target.value = '';
}

async function exportAllData(){
  const data = {
    records: (await dbGetAll('records')).filter(r=>r.userId===currentUserId),
    wrongQuestions: (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId),
    favorites: (await dbGetAll('favorites')).filter(f=>f.userId===currentUserId),
    notes: (await dbGetAll('notes')).filter(n=>n.userId===currentUserId),
    questions: await dbGetAll('questions'),
    users: await dbGetAll('users'),
    exportTime: new Date().toISOString(),
    version: '1.0'
  };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type:'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `xuecheng_backup_${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(a.href);
}

async function importQuestions(event){
  const file = event.target.files[0];
  if(!file) return;
  try{
    const text = await file.text();
    const data = JSON.parse(text);
    const arr = Array.isArray(data) ? data : [data];
    let count = 0;
    for(const q of arr){
      if(!q.id) q.id = `imp_${Date.now()}_${count}`;
      await dbAdd('questions', q);
      count++;
    }
    await reloadQuestions();
    alert(`成功导入 ${count} 道题目`);
    renderSettings();
  }catch(e){
    alert('导入失败：'+e.message);
  }
  event.target.value = '';
}

async function reloadQuestions(){
  const imported = await dbGetAll('questions');
  // 合并：样例题 + 导入题（按 id 去重，导入题优先）
  const map = new Map();
  SAMPLE_QUESTIONS.forEach(q=>map.set(q.id, q));
  imported.forEach(q=>map.set(q.id, q));
  allQuestions = Array.from(map.values());
}

async function clearAllData(){
  if(!confirm('确定要清空当前用户的所有数据吗？此操作不可恢复！')) return;
  if(!confirm('再次确认：将清除你的所有刷题记录、错题、收藏和笔记！')) return;
  const all = {
    records: (await dbGetAll('records')).filter(r=>r.userId===currentUserId),
    wrongQuestions: (await dbGetAll('wrongQuestions')).filter(w=>w.userId===currentUserId),
    favorites: (await dbGetAll('favorites')).filter(f=>f.userId===currentUserId),
    notes: (await dbGetAll('notes')).filter(n=>n.userId===currentUserId)
  };
  for(const r of all.records) await dbDelete('records', r.id);
  for(const w of all.wrongQuestions) await dbDelete('wrongQuestions', w.id);
  for(const f of all.favorites) await dbDelete('favorites', f.id);
  for(const n of all.notes) await dbDelete('notes', n.id);
  await updateWrongBadge();
  await updateUserStreak();
  alert('已清空当前用户所有数据');
  switchPanel('home');
}

/* ==========================================================
 * 3.17 初始化
 * ========================================================== */
async function init(){
  try{
    await initDB();
  }catch(e){
    console.error('数据库初始化失败', e);
    document.getElementById('homeContent').innerHTML = '<div class="empty-state"><div class="es-icon">⚠️</div><p>数据库初始化失败，请使用支持 IndexedDB 的浏览器</p></div>';
    return;
  }

  // 加载或创建默认用户
  let users = await dbGetAll('users');
  if(users.length===0){
    await dbAdd('users', { id:1, name:'Rosy1003', createdDate:new Date().toISOString() });
    users = [{ id:1, name:'Rosy1003' }];
  }
  // 确保当前用户存在
  const exists = users.some(u=>u.id===currentUserId);
  if(!exists){
    currentUserId = users[0].id;
    currentUserName = users[0].name;
  } else {
    const u = users.find(u=>u.id===currentUserId);
    if(u) currentUserName = u.name;
  }

  // 合并样例题与导入题
  await reloadQuestions();

  // 加载用户设置
  await loadUserSettings();

  // 更新界面
  await updateUserDisplay();
  await updateWrongBadge();

  // 渲染首页
  renderHome();

  // 事件监听：点击遮罩关闭弹窗
  const modal = document.getElementById('noteModal');
  if(modal){
    modal.addEventListener('click', (e)=>{
      if(e.target === modal) closeNoteModal();
    });
  }
  // 点击其他地方关闭用户下拉
  document.addEventListener('click', (e)=>{
    const dd = document.getElementById('userDropdown');
    if(dd && dd.classList.contains('show') && !e.target.closest('.user-switch') && !e.target.closest('.user-dropdown')){
      dd.classList.remove('show');
    }
  });
}

document.addEventListener('DOMContentLoaded', init);
